---
# author: Paul Armstrong (parmstro)
# date: 2023-03-13
# purpose: ensure list of packages is installed.

- name: "Ensure the list of tools is installed"
  ansible.builtin.yum:
    name: "{{ tl.list }}"
    state: present
