---
# author: Paul Armstrong (parmstro)
# date: 2023-03-13
# purpose: "Ensure the defined sudo command is configured"

- name: "Ensure the defined sudo command is configured"
  redhat.rhel_idm.ipasudocmd:
    ipaadmin_password: "{{ ipaadmin_password }}"
    ipaadmin_principal: "{{ ipaadmin_principal | default(omit) }}"
    name: "{{ ipasudocommand.commandname }}"
    state: present
    description: "{{ ipasudocommand.description }}"
